### ISSUE TITLE
No module named ...

### ISSUE THREAD

**Issue by WerWojtas** [aghbit/Algorytmy-Geometryczne#28]
Nie da się zaimportować testów i wizualizacji w Jupyterze

**Comment by mdbrnowski** [comment]
@WerWojtas Upewnij się, że wykonałaś te instrukcje, które są dodane w README. Będąc w katalogu repozytorium, należy stworzyć dystrybuję (`python3 setup.py sdist`). Następnie należy zainstalować pakiet (`pip install -e .`).

Jaki dokładnie błąd się wyświetla (nazwa modułu "...")? W którym labie występuje błąd?

**Comment by WerWojtas** [comment]
A labie1, wykonałam te instrukcje i jest napisane, że "Nie mo"

**Comment by mdbrnowski** [comment]
Podsumowując: instalujemy `bitalg` w tym samym pythonie, w których uruchamiamy Jupytera (warto może przy okazji ograniczyć liczbę zainstalowanych dystrybucji na komputerze xD). Jak dodam requirements, pewnie będzie też trochę prościej nad tym zapanować.
PS: kropka na końcu `pip install -e .` **ma** znaczenie.
